// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/19/2026, 3:30:21 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/david/workspace/viral-happiness/www/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/plugins/**/*.{js,ts,mjs}","/home/david/workspace/viral-happiness/www/app/composables/**/*.{js,ts,mjs}","/home/david/workspace/viral-happiness/www/app/utils/**/*.{js,ts,mjs}","/home/david/workspace/viral-happiness/www/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/david/workspace/viral-happiness/www/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;